In [5]:
import numpy as np

In [2]:
my_list = [1,2,3]

Cast the list into an array usong Numpy

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

You can create a 2 dimension array using numpy

In [8]:
may_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(may_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Diferente ways to create an array

In [10]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

Identity matrix

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])